set nu
set smartindent
set fileencodings=utf-8,gb2312,gbk,gb18030
set cscopequickfix=s-,c-,d-,i-,t-,e-
set cst
set hls
set ruler
filetype plugin on
:nmap <C-\>s :cs f s <C-R><C-W><CR>
:nmap <C-\>t :cs f t <C-R><C-W><CR>
:nmap <C-\>c :cs f c <C-R><C-W><CR>
:nmap <C-\>d :cs f d <C-R><C-W><CR>
"colorscheme retrobox
"colorscheme torte
"colorscheme darkblue
"colorscheme desert
"colorscheme lunaperche
colorscheme zaibatsu
syntax on
